_wandb:
    value:
        cli_version: 0.21.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "3":
                - 14
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
alpha:
    value: 0.01
beta:
    value: 0.0001
eta:
    value: 0.125
exploration_fraction:
    value: 0.2
num_episodes:
    value: 500
