_wandb:
    value:
        cli_version: 0.21.0
        e:
            tlkle1khuj4mvxaxt0cd2vhz9xq3bbct:
                args:
                    - sweep
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2013991550976"
                        used: "61653004288"
                email: ai4vijay@gmail.com
                executable: /home/vijay/Desktop/rp2/.venv/bin/python
                git:
                    commit: d476cf5a46e569d8b335349260b81f2131923f02
                    remote: git@github.com:ai4vijay-sriv/rp2.git
                gpu: NVIDIA RTX 4000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 6144
                      memoryTotal: "21469593600"
                      name: NVIDIA RTX 4000 Ada Generation
                      uuid: GPU-80e4141e-ed7b-fa07-3e9a-8818763a7e25
                host: scl-3
                memory:
                    total: "134825361408"
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: -m cql.testing
                python: CPython 3.10.18
                root: /home/vijay/Desktop/rp2
                startedAt: "2025-08-10T20:41:16.982842Z"
                writerId: tlkle1khuj4mvxaxt0cd2vhz9xq3bbct
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
alpha:
    value: 0.0001
beta:
    value: 0.0001
eta:
    value: 0.125
exploration_fraction:
    value: 0.2
num_episodes:
    value: 1000
